"""Pinned cross-check cases, shared by the Python and Rust sides.

Both sides must agree on every parameter. `compare.py` asserts the `#` header lines match,
so drift between the two definitions is caught rather than silently compared.

Random configurations are generated by SplitMix64, implemented identically in both
languages, so the two sides see bit-identical inputs. Using each side's native RNG would
make the comparison meaningless.
"""

MASK64 = (1 << 64) - 1


def splitmix64(state):
    """Yields (new_state, u64). Reference implementation; mirrored in src/bin/xcheck.rs."""
    state = (state + 0x9E3779B97F4A7C15) & MASK64
    z = state
    z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & MASK64
    z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & MASK64
    z = z ^ (z >> 31)
    return state, z


class Rng:
    def __init__(self, seed):
        self.s = seed & MASK64

    def next_u64(self):
        self.s, z = splitmix64(self.s)
        return z

    def unit(self):
        """u64 -> [0,1) via the top 53 bits. Exact in both languages."""
        return (self.next_u64() >> 11) * (2.0 ** -53)

    def range(self, lo, hi):
        return lo + (hi - lo) * self.unit()


def random_configs(n, seed):
    """n configurations, positions in [-4,4), velocities in [-1,1).

    Deliberately unconstrained: no COM correction, no scale normalisation. The point is to
    exercise the algebra over a wide spread of geometries, including near-degenerate ones.
    """
    rng = Rng(seed)
    out = []
    for _ in range(n):
        r = [[rng.range(-4.0, 4.0), rng.range(-4.0, 4.0)] for _ in range(3)]
        v = [[rng.range(-1.0, 1.0), rng.range(-1.0, 1.0)] for _ in range(3)]
        out.append((r, v))
    return out


CASES = {
    "algebra": dict(
        kind="algebra",
        n=256,
        seed=20260822,
        columns="idx,energy,d01,d02,d12,inertia,hyperradius,n0,n1,n2",
    ),
}


def header_lines(name):
    c = CASES[name]
    return [
        f"# case={name} kind={c['kind']} n={c['n']} seed={c['seed']}",
        "# masses=3,4,5 G=1 eps2=0",
        f"# columns={c['columns']}",
    ]
