"""Pinned cross-check cases, shared by the Python and Rust sides.

Both sides must agree on every parameter. `compare.py` asserts the `#` header lines match,
so drift between the two definitions is caught rather than silently compared.

Random configurations are generated by SplitMix64, implemented identically in both
languages, so the two sides see bit-identical inputs. Using each side's native RNG would
make the comparison meaningless.
"""

MASK64 = (1 << 64) - 1


def splitmix64(state):
    """Yields (new_state, u64). Reference implementation; mirrored in src/bin/xcheck.rs."""
    state = (state + 0x9E3779B97F4A7C15) & MASK64
    z = state
    z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & MASK64
    z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & MASK64
    z = z ^ (z >> 31)
    return state, z


class Rng:
    def __init__(self, seed):
        self.s = seed & MASK64

    def next_u64(self):
        self.s, z = splitmix64(self.s)
        return z

    def unit(self):
        """u64 -> [0,1) via the top 53 bits. Exact in both languages."""
        return (self.next_u64() >> 11) * (2.0 ** -53)

    def range(self, lo, hi):
        return lo + (hi - lo) * self.unit()


def random_configs(n, seed):
    """n configurations, positions in [-4,4), velocities in [-1,1).

    Deliberately unconstrained: no COM correction, no scale normalisation. The point is to
    exercise the algebra over a wide spread of geometries, including near-degenerate ones.
    """
    rng = Rng(seed)
    out = []
    for _ in range(n):
        r = [[rng.range(-4.0, 4.0), rng.range(-4.0, 4.0)] for _ in range(3)]
        v = [[rng.range(-1.0, 1.0), rng.range(-1.0, 1.0)] for _ in range(3)]
        out.append((r, v))
    return out


# Fixed physical length of one sync sub-interval. n_sync is derived from it so that every
# horizon in the divergence sweep is integrated at the SAME per-interval resolution.
# Leaving n_sync fixed while t_max varies would compare two different discretisations, and
# the divergence curve would then measure the discretisation rather than the chaos.
SYNC_INTERVAL = 13.0 / 32.0

AZ_BASE_COLUMNS = (
    "idx,r0x,r0y,r1x,r1y,r2x,r2y,v0x,v0y,v1x,v1y,v2x,v2y,t,dmin_ref,drift,switches"
)


def n_sync_for(t_max):
    return max(1, int(round(t_max / SYNC_INTERVAL)))


def az_columns(t_max):
    """Base columns plus one column per sync boundary carrying the chosen reference body.

    Comparing the reference body per sync is not optional. `choose_reference` is an argmax
    over pair distances; if Rust and NumPy break a near-tie differently the trajectories
    diverge for a reason that is not a bug, and it would present as an AZ transcription
    error. Making it a compared column tells the two apart immediately.
    """
    refs = ",".join("ref%02d" % k for k in range(n_sync_for(t_max)))
    return AZ_BASE_COLUMNS + "," + refs


def _az_case(t_max, nx=3, ny=3):
    return dict(
        kind="az",
        nx=nx, ny=ny, cx=1.0, cy=3.0, half=0.05, body=0,
        t_max=t_max, n_sync=n_sync_for(t_max), eta=0.01, max_steps=30000,
        columns=az_columns(t_max),
    )


CASES = {
    "algebra": dict(
        kind="algebra",
        n=256,
        seed=20260822,
        columns="idx,energy,d01,d02,d12,inertia,hyperradius,n0,n1,n2",
    ),
    # The horizon sweep. Same settings, increasing t_max: a correct port shows divergence
    # growing like exp(lambda t) from an O(1e-16) intercept.
    "az_t0p5": _az_case(0.5),
    "az_t1": _az_case(1.0),
    "az_t2": _az_case(2.0),
    "az_t4": _az_case(4.0),
    "az_t8": _az_case(8.0),
    "az_t13": _az_case(13.0),
    # Benettin FTLE + the diffusion regression, on tb.py's fixed-step leapfrog -- the pair
    # `tb_ftle.py` is actually built on, and therefore the only pair with a reference.
    #
    # The perturbation DIRECTION is pinned analytically rather than drawn: numpy's Ziggurat is
    # not ported, and reproducing it is not required. The direction only seeds the shadow, and
    # a comparison needs both sides to use the same one. The Python side substitutes it into
    # `tb_ftle.integrate_full` without touching the reference's own code path.
    "ftle": dict(
        kind="ftle",
        nx=4, ny=4, cx=1.0, cy=3.0, half=0.05, body=0,
        t_max=2.0, dt=1e-4, eps=0.03, d0=1e-8,
        renorm_every=200, sample_every=25,
        columns="idx,ftle,diffusion,dmin,nre,S,rx0,ry0",
    ),
}

# The pinned perturbation, flat over (body, axis). Normalised by the reference itself.
FTLE_PERT = [1.0, -2.0, 3.0, -4.0, 5.0, -6.0]

AZ_HORIZONS = ["az_t0p5", "az_t1", "az_t2", "az_t4", "az_t8", "az_t13"]


def dtau_mode():
    """The step-sizing mode, from `PRIN_DTAU_MODE`, defaulting to the shipped one.

    Both sides carry the same `dtau` defect and both were fixed, so the comparison that means
    anything is old-against-old AND new-against-new -- either alone would pass while the two
    transcriptions diverged. It is emitted into the header, and `compare.py` asserts headers
    match, so a mode mismatch between the two sides is a hard failure rather than a quiet
    disagreement.
    """
    import os
    m = os.environ.get("PRIN_DTAU_MODE", "") or "per-step-interval"
    if m not in ("fixed", "per-step-remaining", "per-step-interval"):
        raise SystemExit(f"PRIN_DTAU_MODE: unexpected value {m!r}")
    return m


def header_lines(name):
    c = CASES[name]
    if c["kind"] == "algebra":
        head = [
            f"# case={name} kind={c['kind']} n={c['n']} seed={c['seed']}",
            "# masses=3,4,5 G=1 eps2=0",
        ]
    elif c["kind"] == "ftle":
        head = [
            f"# case={name} kind={c['kind']} nx={c['nx']} ny={c['ny']}"
            f" cx={c['cx']} cy={c['cy']} half={c['half']} body={c['body']}",
            f"# t_max={c['t_max']} dt={c['dt']} eps={c['eps']} d0={c['d0']}"
            f" renorm_every={c['renorm_every']} sample_every={c['sample_every']}"
            f" masses=3,4,5 G=1 pert={','.join(str(x) for x in FTLE_PERT)}",
        ]
    else:
        head = [
            f"# case={name} kind={c['kind']} nx={c['nx']} ny={c['ny']}"
            f" cx={c['cx']} cy={c['cy']} half={c['half']} body={c['body']}",
            f"# t_max={c['t_max']} n_sync={c['n_sync']} eta={c['eta']}"
            f" max_steps={c['max_steps']} masses=3,4,5 G=1 ens=0"
            f" dtau_mode={dtau_mode()}",
        ]
    return head + [f"# columns={c['columns']}"]
